Make tls features additive
clux/kube-rs pull request #383
Opened 2021-01-10 13:04 UTC by MikailBag

Changes: create an enum with available TLS backends. Library user explicitly chooses it and passes it to kube.

Draft: I haven't updated reqwest & websocket creation code yet.

2021-01-10 13:23 UTC, MikailBag commented
Turns out, `async-tungstenite` does not currently support several TLS backends. If several features are enabled, it just selects one.

2021-01-10 13:31 UTC, MikailBag commented
Filed https://github.com/sdroege/async-tungstenite/issues/78

2021-01-10 14:11 UTC, clux requested changes
comments

2021-01-10 14:11 UTC, clux commented on kube/src/tls.rs
> +    Rustls,
comments here are switched around

2021-01-10 14:11 UTC, clux commented on kube/src/tls.rs
> +    /// is only intended to use in tests.
This seems to be used in examples as a main interface contrary to this comment.

2021-01-10 14:11 UTC, clux commented on kube/src/tls.rs
> +        unreachable!()
Because this is an interface for `Client` construction, this effectively pushes a compile time error to a runtime error?

2021-01-10 14:11 UTC, clux commented on kube/src/client/mod.rs
> +    pub async fn try_default(tls: Tls) -> Result<Self> {
Having an argument to `try_default` makes it no longer a default.

2021-01-10 14:12 UTC, clux commented
This is an interesting one, thanks for doing this. I like the way this factors out tls into its own module, it was starting to grow infect a lot of other files. I am a bit on the fence of the `Tls::pick` mechanism as it stands. Left some questions.

2021-01-10 14:16 UTC, clux commented
One point here: having this be a non-additive feature gave us a guarantee that you only got one of the TLS stacks into the dependency trees if it built. In an additive mode, we run the risk of multiple kube uses in various `Cargo.toml`s selecting multiple stacks.

2021-01-10 15:26 UTC, MikailBag commented
Regarding `Tls::pick`, it can still be written in a compile-time-checked way (with smth like `#[cfg(or(and(rustls, not(openssl))), and(openssl, not(rustls)))]`). I've imagined it as `doc(hidden)` test-utility so I've chosen dynamic checking because it's easier to implement.

> In an additive mode, we run the risk of multiple kube uses in various Cargo.tomls selecting multiple stacks.

2021-01-10 15:32 UTC, teozkr commented
To be honest, I don't really see the point of the current selection mechanism. Of the two provided backends, Rustls is generally Better (supports more modern features like HTTP/2, is more consistent across platforms, and is arguably more trustworthy because more of it is auditable and Rust). If we want to have an escape hatch for when that might not work (which I'd kind of agree with), then IMO that should be something more open-ended, like Hyper's [`Connect`](https://docs.rs/hyper/0.14.2/hyper/client/connect/trait.Connect.html) trait.

> One point here: having this be a non-additive feature gave us a guarantee that you only got one of the TLS stacks into the dependency trees if it built. In an additive mode, we run the risk of multiple kube uses in various Cargo.tomls selecting multiple stacks.

IMO, this is really a con of the current approach. Library crates that depend on `kube` either need to pick a backend (which will make it hard-conflict with crates that depend on the other backend), or it will need to depend with `default-features = false` (easy to forget), and require the leaf (application) crate to depend on `kube` and opt into the preferred backend.

2021-01-10 15:37 UTC, MikailBag commented
Anyway, this PR is blocked on the `async-tungstenite` issue, so I'd prefer to fix this PR later when it's unblocked.

2021-03-02 10:26 UTC, clux commented
> To be honest, I don't really see the point of the current selection mechanism. Of the two provided backends, Rustls is generally Better (supports more modern features like HTTP/2, is more consistent across platforms, and is arguably more trustworthy because more of it is auditable and Rust).

Yes, I agree, and hope that we can move towards rustls as a general rust default in the future, but due to bugs like #153, it's really viable to drop openssl. Also a bit hesitant to be the first mover on such a change.

@MikailBag : While `async_tungstenite` has been swapped out for `tokio_tungstenite` - so this might be theoretically possible - I think it's probably best we put a pin in this one for now unless we can find something more ergonomic when rusttls is sufficiently compatible. Until then, I would prefer the compile time selection for the safety it provides.

Closing for now, but feel free to re-open to discuss further.

2021-03-02 10:26 UTC, closed without merging

2021-03-02 11:24 UTC, kazk commented
> should be something more open-ended, like Hyper's [`Connect`](https://docs.rs/hyper/0.14.2/hyper/client/connect/trait.Connect.html) trait.

Yeah, we're already using it internally in `kube::Service` composing `TimeoutConnector` and `HttpsConnector`.

```rust
let connector = ServiceBuilder::new().layer(timeout).service(https); // Connect
let client: HyperClient<_, Body> = HyperClient::builder().build(connector);
```

In the future, after figuring out how to let users compose layers nicely, we can optionally let users use custom `HttpsConnector`, and provide functions like `rustls_https` and `native_https` to create `HttpsConnector` from config values to compose with.